#!/usr/bin/env bash
# Corp-OS SessionStart hook — emits a live "boot briefing" as additionalContext so
# the CEO greets with an accurate 3-line state-of-the-company on its FIRST reply,
# without having to run the board queries itself. Registered in .claude/settings.json.
# Always exits 0 — a hook must never block session start.
set -uo pipefail
DIR="${CLAUDE_PROJECT_DIR:-$(pwd)}"
cd "$DIR" 2>/dev/null || true

stats="$(python3 pm/pm.py stats 2>/dev/null)"
overdue="$(python3 pm/pm.py overdue 2>/dev/null)"
tasks="$(python3 pm/pm.py list 2>/dev/null | head -n 40)"
decisions="$(tail -n 15 memory/decisions.md 2>/dev/null)"
imported=""
if compgen -G "memory/imported/*/MIGRATION_REPORT.md" >/dev/null 2>&1; then
  imported="Unmerged legacy migration report present: $(ls -1 memory/imported/*/MIGRATION_REPORT.md 2>/dev/null | head -1) — consider the 'Onboard legacy knowledge' task."
fi

read -r -d '' CTX <<EOF || true
SESSION BOOT BRIEFING — auto-generated by the Corp-OS SessionStart hook.
Per your charter's boot protocol, on your FIRST reply this session, greet the Chairman with a 3-line
state-of-the-company (board summary · top risk · top opportunity) using the LIVE data below.
You need not re-run these commands unless you want more detail.

[BOARD STATS]
$stats

[OVERDUE]
$overdue

[TASKS]
$tasks

[RECENT DECISIONS (tail)]
$decisions

$imported
EOF

python3 - "$CTX" <<'PY'
import json, sys
print(json.dumps({"hookSpecificOutput": {
    "hookEventName": "SessionStart",
    "additionalContext": sys.argv[1],
}}))
PY
